services:
  rag-api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
      - ./data:/data
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    networks:
      - rag-network
    depends_on:
      - qdrant
      - redis

  chat-interface:
    image: python:3.9-slim
    working_dir: /app
    ports:
      - "8501:8501"
    volumes:
      - ./app/streamlit_app.py:/app/streamlit_app.py
    command: sh -c "pip install streamlit requests && streamlit run streamlit_app.py --server.address=0.0.0.0"
    networks:
      - rag-network
    depends_on:
      - rag-api

  qdrant:
    image: qdrant/qdrant:v1.7.4
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - ./qdrant_storage:/qdrant/storage
    networks:
      - rag-network
    restart: unless-stopped

  redis:
    image: redis:7.2-alpine
    ports:
      - "6379:6379"
    volumes:
      - ./redis_data:/data
    networks:
      - rag-network
    restart: unless-stopped

networks:
  rag-network:
    driver: bridge